server:
 port: 8000
 forward-headers-strategy: framework
# ssl:
#  key-store: classpath:keystore/key.jks
#  key-store-password: Leonardpark2023

spring:
 devtools:
  add-properties: true
 data:
  mongodb:
   host: localhost
   port: 27017
   database: ffmpeg
  redis:
   database: 0
   host: localhost
   port: 6379
   password:
   jedis:
    pool:
     max-active: 8
     max-wait: -1ms
     max-idle: 8
     min-idle: 0
 main:
  allow-bean-definition-overriding: true
 mvc:
  pathmatch:
   matching-strategy: ant_path_matcher
 servlet:
  multipart:
   max-file-size: -1
   max-request-size: -1

auditLog:
 enable: true

ffmpeg:
 dir: /Users/leowu/Desktop/ffmpeg-springboot-data

email:
 debug: false
 host: smtp.gmail.com
 port: 587
 sender:
  email: leonardpark.server@gmail.com
  password: irynxjmnumiodhor
  from: ffmpeg@leonardpark.dev
 smtp:
  auth: true
  starttls:
   enable: true
 transport:
  protocols: smtp



